ALTER TABLE `messages` ADD `forwarding_score` integer;--> statement-breakpoint
ALTER TABLE `messages` ADD `is_view_once` integer;--> statement-breakpoint
ALTER TABLE `messages` ADD `ephemeral_expiration` integer;--> statement-breakpoint
ALTER TABLE `messages` ADD `broadcast` integer;--> statement-breakpoint
ALTER TABLE `messages` ADD `push_name` text;--> statement-breakpoint
ALTER TABLE `messages` ADD `seconds` integer;--> statement-breakpoint
ALTER TABLE `messages` ADD `ptt` integer;--> statement-breakpoint
ALTER TABLE `messages` ADD `is_animated` integer;--> statement-breakpoint
ALTER TABLE `messages` ADD `jpeg_thumbnail` text;--> statement-breakpoint
ALTER TABLE `messages` ADD `poll_name` text;--> statement-breakpoint
ALTER TABLE `messages` ADD `poll_values` text;--> statement-breakpoint
ALTER TABLE `messages` ADD `selectable_count` integer;--> statement-breakpoint
ALTER TABLE `messages` ADD `group_jid` text;--> statement-breakpoint
ALTER TABLE `messages` ADD `group_name` text;--> statement-breakpoint
ALTER TABLE `messages` ADD `invite_code` text;--> statement-breakpoint
ALTER TABLE `messages` ADD `invite_expiration` integer;--> statement-breakpoint
ALTER TABLE `messages` ADD `selected_button_id` text;--> statement-breakpoint
ALTER TABLE `messages` ADD `selected_list_option` text;--> statement-breakpoint
ALTER TABLE `messages` ADD `template_button_selected_id` text;--> statement-breakpoint
ALTER TABLE `messages` ADD `native_flow_response` text;--> statement-breakpoint
ALTER TABLE `messages` ADD `order_id` text;--> statement-breakpoint
ALTER TABLE `messages` ADD `order_headline` text;--> statement-breakpoint
ALTER TABLE `messages` ADD `order_note` text;